### ISSUE TITLE
Test Matrix fails with SIGSEGV when HELIB_DEBUG-ON

### ISSUE THREAD

**Issue by esteffin** [helibproject/HElib#38]
TestMatrixWithCtxt.MultiplyTwoCtxtMatrices fails with SIGSEGV when HELIB_DEBUG-ON

**Comment by esteffin** [comment]
GDB stack trace

```bash
(gdb) r --gtest_filter="*MultiplyTwoCtxtMatrices*"
Starting program: ./build/bin/runTests --gtest_filter="*MultiplyTwoCtxtMatrices*"
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7facd41c1700 (LWP 300406)]
*** Bound N=13723, choosing m=14009, phi(m)=14008
*** Bound N=13723, choosing m=14009, phi(m)=14008
random seed: 1757335897
Note: Google Test filter = *MultiplyTwoCtxtMatrices*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from various_parameters/TestMatrixWithCtxt
[ RUN      ] various_parameters/TestMatrixWithCtxt.MultiplyTwoCtxtMatrices/0

Thread 1 "runTests" received signal SIGSEGV, Segmentation fault.
helib::PubKey::getContext (this=this@entry=0x0)
    at ./src/keys.cpp:269
269	const Context& PubKey::getContext() const { return context; }
(gdb) bt
#0  helib::PubKey::getContext (this=this@entry=0x0)
    at ./src/keys.cpp:269
#1  0x00007facd4bab75f in helib::SecKey::Decrypt (this=0x0, plaintxt=..., ciphertxt=..., f=...)
    at ./include/helib/Ctxt.h:1194
#2  0x00007facd4b4164e in helib::embeddingLargestCoeff (ctxt=..., sk=...)
    at ./src/debugging.cpp:61
#3  0x00007facd4b417c6 in helib::realToEstimatedNoise (ctxt=..., sk=...)
    at ./src/debugging.cpp:31
#4  0x00007facd4b41868 in helib::checkNoise (ctxt=..., sk=..., msg="reLinearize 140724841565280", thresh=10)
    at ./src/debugging.cpp:51
#5  0x00007facd4b38eec in helib::Ctxt::multiplyBy (this=this@entry=0x7ffd0e314c60, other=...)
    at /usr/include/c++/9/bits/char_traits.h:300
#6  0x00005592a60a8fbc in helib::Ctxt::operator*= (other=..., this=0x7ffd0e314c60)
    at ./include/helib/Ctxt.h:456
#7  helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0>(helib::Tensor<helib::Ctxt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1}::operator()(long, long) const (this=0x7ffd0e314e90, first=<optimized out>, 
    last=1)
    at ./include/helib/Matrix.h:528
#8  0x00005592a60a34a9 in NTL::BasicThreadPool::runOneTask (task=task@entry=0x7ffd0e314ed0, index=index@entry=0)
    at /usr/include/NTL/BasicThreadPool.h:392
#9  0x00005592a60aab3a in NTL::BasicThreadPool::exec_range<helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0>(helib::Tensor<helib::Ctxt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1}>(long, helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0>(helib::Tensor<helib::Ctxt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1} const&) (fct=..., sz=<optimized out>, this=0x5592a7a331b0)
    at /usr/include/NTL/BasicThreadPool.h:551
#10 NTL::BasicThreadPool::exec_range<helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0>(helib::Tensor<helib::Ctxt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1}>(long, helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0>(helib::Tensor<helib::Ctxt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1} const&) (fct=..., sz=<optimized out>, this=0x5592a7a331b0) at /usr/include/NTL/BasicThreadPool.h:540
--Type <RET> for more, q to quit, c to continue without paging--
txt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1}>(NTL::BasicThreadPool*, long, helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0>(helib::Tensor<helib::Ctxt, 2ul> const&, helib::Tensor<helib::Ctxt, 2ul> const&)::{lambda(long, long)#1} const&) (fct=..., sz=<optimized out>, pool=0x5592a7a331b0) at /usr/include/NTL/BasicThreadPool.h:564
#12 helib::operator*<helib::Ctxt, helib::Ctxt, (void*)0> (M1=..., M2=...)
    at ./include/helib/Matrix.h:521
#13 0x00005592a60a14fd in (anonymous namespace)::TestMatrixWithCtxt_MultiplyTwoCtxtMatrices_Test::TestBody (this=0x5592a7b338f0)
    at ./tests/TestMatrix.cpp:1054
#14 0x00005592a6197c91 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x5592a61e6150 "the test body", method=<optimized out>, 
    object=0x5592a7b338f0)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2414
#15 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x5592a7b338f0, method=<optimized out>, 
    location=location@entry=0x5592a61e6150 "the test body")
    at ./build/src/googletest-src/googletest/src/gtest.cc:2469
#16 0x00005592a618c1d6 in testing::Test::Run (this=this@entry=0x5592a7b338f0)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2508
#17 0x00005592a618c472 in testing::Test::Run (this=0x5592a7b338f0)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2684
#18 testing::TestInfo::Run (this=0x5592a7a94e70)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2684
#19 0x00005592a618c61c in testing::TestInfo::Run (this=<optimized out>)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2658
#20 testing::TestSuite::Run (this=0x5592a7a94880)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2816
#21 0x00005592a618cdf3 in testing::TestSuite::Run (this=<optimized out>)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2796
#22 testing::internal::UnitTestImpl::RunAllTests (this=0x5592a7a2c3b0)
    at ./build/src/googletest-src/googletest/src/gtest.cc:5338
#23 0x00005592a6198201 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (
    location=0x5592a61e7598 "auxiliary test code (environments or event listeners)", method=<optimized out>, object=0x5592a7a2c3b0)
    at ./build/src/googletest-src/googletest/src/gtest.cc:2414
#24 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5592a7a2c3b0, method=<optimized out>, 
    location=location@entry=0x5592a61e7598 "auxiliary test code (environments or event listeners)")
    at ./build/src/googletest-src/googletest/src/gtest.cc:2469
#25 0x00005592a618cf85 in testing::UnitTest::Run (this=0x5592a62aa520 <testing::UnitTest::GetInstance()::instance>)
    at ./build/src/googletest-src/googletest/include/gtest/gtest.h:1412
#26 0x00005592a5eeec53 in RUN_ALL_TESTS ()
    at ./build/src/googletest-src/googletest/include/gtest/gtest.h:2473
#27 main (argc=<optimized out>, argv=0x7ffd0e315848) at ./tests/main.cpp:22
```
